[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]
