set-option -sa terminal-overrides ",xterm*:Tc"
# Enable mouse
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

set -g @plugin 'christoomey/vim-tmux-navigator'

# THEME START
set -g @plugin 'o0th/tmux-nova'
# Fonts
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 
# --- Gotham Color Scheme---
set -g @nova-pane-active-border-style "#ffffff"
set -g @nova-pane-border-style "#222222"
set -g @nova-status-style-bg "#0C1014"
set -g @nova-status-style-fg "#99D1CE"
set -g @nova-status-style-active-bg "#EDB443"
set -g @nova-status-style-active-fg "#000000"
set -g @nova-status-style-double-bg "#000000"
set -g @nova-segment-mode-colors "#C23127 #000000"
set -g @nova-segment-whoami-colors "#C23127 #000000"
# Layout
set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"
set -g @nova-segment-mode "#{?client_prefix,Α,α}"
set -g @nova-segment-whoami "أحمد"
set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"
# THEME END

# Set vi-mode
set-window-option -g mode-keys vi

# Keybindings for selection mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Create panes from CWD
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
