# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
font_size	     22
bold_font        auto
italic_font      auto
bold_italic_font auto

# Arabic Symbols (U+0600-U+06FF for core only)
symbol_map U+0600-U+06FF,U+0750-U+077F,U+08A0-U+08FF,U+FB50-U+FDFF,U+FE70-U+FEFF,U+10E60-U+10E7F DejaVuSansM Nerd Font Mono
# END_KITTY_FONTS

# BEGIN_KITTY_CURSOR
allow_remote_control yes
# END_KITTY_CURSOR

# START_KITTY_TAB
tab_bar_style powerline
tab_powerline_style slanted
# END_KITTY_TAB

# START_KITTY_SHORTCUTS
map ctrl+shift+t new_tab_with_cwd
# END_KITTY_SHORTCUTS

scrollbar_width 0.35

mouse_hide_wait 1.5

enable_audio_bell no

hide_window_decorations yes

# Open scrollback in a new window using Neovim
scrollback_pager nvim -c "set signcolumn=no showtabline=0" -c "silent! %s/\s\+$//e" -c "map q :qa!<CR>" -c "autocmd TermOpen * startinsert" -c "set clipboard+=unnamedplus" -
