# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_FONTS
font_family      family="DejaVuSansM Nerd Font Mono"
font_size	22
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_CURSOR
allow_remote_control yes
# END_KITTY_CURSOR

# START_KITTY_TAB
tab_bar_style powerline
tab_powerline_style slanted
# END_KITTY_TAB

# START_KITTY_SHORTCUTS
map ctrl+shift+t new_tab_with_cwd
# END_KITTY_SHORTCUTS

scrollbar_width 0.35

mouse_hide_wait 1.5

enable_audio_bell no

hide_window_decorations yes

# Open scrollback in a new window using Neovim
scrollback_pager nvim -c "set signcolumn=no showtabline=0" -c "silent! %s/\s\+$//e" -c "map q :qa!<CR>" -c "autocmd TermOpen * startinsert" -c "set clipboard+=unnamedplus" -
